### ISSUE TITLE
Add Travis-CI to automate testing after commits and pull requests.

### ISSUE THREAD

**Issue by mroberge** [stijnvanhoey/hydropy#3]

**Comment by mroberge** [comment]
I think at this point @stijnvanhoey  you'll need to go to Travis-CI, log in using your github account, and then find this repository on your Travis profile page and activate it.  I poked around, and I don't think I can do it, since this is your repository.

**Comment by stijnvanhoey** [comment]
Travis is linked and active now, however giving errors. It is a matter of fixing these and writing proper unit tests now for the functionalities. Closing this issue here.

**Comment by mroberge** [comment]
Great!  I'll take a look and see what I can do.
