### ISSUE TITLE
Add a simple system for requesting USGS data

### ISSUE THREAD

**Issue by mroberge** [stijnvanhoey/hydropy#4]
Keep this simple at first- just a function that returns a dataframe.

**Comment by stijnvanhoey** [comment]
I suggest to include this function into the [third_party_data](https://github.com/stijnvanhoey/hydropy/blob/master/hydropy/reading_third_party_data.py) script, which already provides functions to read in partner data. 

Simple function (that creates a dframe or directly HydroAnalysis-object) will indeed do the job for now. However, we should maybe create a ThirdParty base class on which the different data-requests can be set up.

**Comment by mroberge** [comment]
Okay.
Also, if VMM has a REST system to access its data, I can write a function for it.  The ftp access would be more difficult, since it seems to require a password.

**Comment by stijnvanhoey** [comment]
In the scope of an earlier project, the access was given with the ftp-server. However, in the future  a webservice would be available as well. i'll fix it when it becomes available.

**Comment by mroberge** [comment]
I'm going to close this now that I've added get_usgs() in merge #8.
