### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by mroberge** [stijnvanhoey/hydropy#9]
Travis has a system that updates the files on PyPI whenever you change the version number. To do this, we can start using version numbers like this: 0.1.1 and feel comfortable about updating the last digit frequently.  To set this up, I'll have to add a couple of things to the travis setup file to trigger the upload, and also add a travis_pypi_setup.py file that I think you'll have to run to enter your pypi password.

**Comment by stijnvanhoey** [comment]
I agree that we could better do this from the start. I'll fix in asap.

**Comment by mroberge** [comment]
I just posted the travis_pypi_setup.py file. To run it, type: `python travis_pypi_setup.py` on the command line and it will ask for your pypi password. It will encrypt the password and save it in the .travis.yml file. After that, every new release will automatically get uploaded to pypi.

**Comment by stijnvanhoey** [comment]
fixed, closing here
